title: hendrikerz.patreonlist::lang.patrons.title
modelClass: HendrikErz\PatreonList\Models\Patron
list: $/hendrikerz/patreonlist/models/patron/columns.yaml
noRecordsMessage: 'backend::lang.list.no_records'
recordUrl: 'hendrikerz/patreonlist/patrons/update/:id'
recordsPerPage: 20
showSetup: true
showCheckboxes: true
defaultSort:
    column: id
    direction: asc
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
filter: config_filter.yaml
