title: Tiers
modelClass: HendrikErz\PatreonList\Models\Tier
list: $/hendrikerz/patreonlist/models/tier/columns.yaml
recordUrl: 'hendrikerz/patreonlist/tiers/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: 20
showSetup: true
showCheckboxes: true
defaultSort:
    column: pledge_amount
    direction: desc
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
